### ISSUE TITLE
복수 변수인 경우 `goals` vs `goalList`

### ISSUE THREAD

**Issue by Hong-been** [Tinkerbell-Green/need-compliments#11]
복수 변수인 경우 `goals` vs `goalList` 이거 의논해서 결정해봐야 겠네요

_Originally posted by @ghtea in https://github.com/Tinkerbell-Green/need-compliments/pull/8#discussion_r819383841_

**Comment by ghtea** [comment]
사실 제가 취업전까지 복수에는 List 를 끝에 붙였는데요, 
그 이유는 List 붙이는게 단수랑 복수랑 덜 헷갈림 + 영어 단어에서 복수형이 단순히 s 만 붙이는게 아닌 단어들이 있어서 그런거 생각하기 싫음
그런데 결국 s만 붙이는게 세상에서 휠씬 더 많이 쓰이는 방식이라 다른곳에서 협업할때 생각하면 s 붙이는 게 나은거 같아요
(List 컴포넌트는 시각적으로 List (목록) 인 컴포넌트로 별개로 생각하고)

**Comment by hotbreakb** [comment]
저는
1. pages 안에 `goals`로 되어있어서
2. list는 안에 item이 있어야 할 거 같아서

라는 이유로 s를 붙이는 게 더 나을 거 같아요. 현업에서 s를 많이 쓴다는 건 새롭게 알게된 사실이네요🤭

**Comment by Hong-been** [comment]
저는 List가 더 눈에 잘 띄고, s는 놓치기 쉽다고생각해서 List를 붙였는데 은지님 말씀(특히 2번)과 더 흔한 컨벤션이라는 말을 들으니까 s가 더 적합한것같습니다! 수정하겠습니다 👍🏻
